Repository Noah4ever/SquirrelAttack, pull requests merged in 2024-06, with the labels that each got.

#36 Feature squirrel entity
  Assets/Animations/Animals/Squirrel/Squirrel.controller
  Assets/Animations/Animals/Squirrel/Squirrel.prefab
  Assets/Models/Animals/Squirrel.fbx
  Assets/Models/Animals/Squirrel.fbx.meta
  Assets/Prefabs/Animals/Squirrel/Squirrel.prefab
  Assets/Prefabs/Animals/Squirrel/Squirrel.prefab.meta
  Assets/Scenes/DevScene.unity
  Assets/Scenes/Templates/BasicScene.scenetemplate
  Assets/Scripts/MoveTo.cs
Labels: 3d model

#35 Feature house logic
  Assets/Scenes/DevScene.unity
  Assets/Scripts/GameController.cs
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/TimeController.cs
  Assets/Scripts/Updateable/Building.cs
  Assets/Scripts/Updateable/Buildings/House.cs
  Assets/Scripts/Updateable/Lifeform.cs
  Assets/Tests/EditMode/HouseTest.cs
  Assets/Tests/EditMode/HouseTest.cs.meta
  Assets/Tests/PlayMode.meta
  Assets/Tests/PlayMode/HouseTest.cs
  Assets/Tests/PlayMode/HouseTest.cs.meta
  Assets/Tests/PlayMode/PlayMode.asmdef
  Assets/Tests/PlayMode/PlayMode.asmdef.meta
Labels: feature

#32 Feature mouse hover
  Assets/Scenes/DevScene.unity
  Assets/Scenes/Templates/BasicScene.scenetemplate
  Assets/Scripts/Clickable/Clickable.cs
  Assets/Scripts/CursorController.cs
  Assets/Scripts/CursorController.cs.meta
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/SelectController.cs
  Assets/Textures.meta
  Assets/Textures/Cursor.meta
  Assets/Textures/Cursor/Cursor Add.png
  Assets/Textures/Cursor/Cursor Add.png.meta
  Assets/Textures/Cursor/Cursor Attack Red.png
  Assets/Textures/Cursor/Cursor Attack Red.png.meta
  Assets/Textures/Cursor/Cursor Default.png
  Assets/Textures/Cursor/Cursor Default.png.meta
  Assets/Textures/Cursor/Cursor Move Up.png
  Assets/Textures/Cursor/Cursor Move Up.png.meta
  Assets/Textures/Cursor/Cursor Target Move B.png
  Assets/Textures/Cursor/Cursor Target Move B.png.meta
  Assets/Textures/Cursor/Cursor impossible.png
  Assets/Textures/Cursor/Cursor impossible.png.meta
  Assets/Textures/Cursor/Cursor possible.png
  Assets/Textures/Cursor/Cursor possible.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: ui

#41 Refactor Hover Logic
  Assets/Scripts/Clickable/Clickable.cs
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/SelectController.cs
Labels: refactor, <1h
